version: '3.7'

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: database
    volumes:
      - ./postgres:/var/lib/postgresql/data
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: node-ts
    expose:
      - ${APP_PORT}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    command: npm run dev
    depends_on:
      - db